import { Inter } from "next/font/google";
import "./globals.css";
import Side from "@/components/sidebar/side";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YOOM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="sides">
          <Side />

          {children}
        </main>
      </body>
    </html>
  );
}
